// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayFIT_DAL.Context;

#nullable disable

namespace StayFIT_DAL.Migrations
{
    [DbContext(typeof(StayFITDbContext))]
    partial class StayFITDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayFIT_CORE.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Et Yemekleri"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Etli Sebze Yemekleri"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tahıllı Yemekler"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Zeytin Yağlı Sebze Yemekleri"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Çorbalar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tatlılar"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Salatalar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Meyveler"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kahvaltılıklar"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Süt ve Süt Ürünleri"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Soğuk İçecekler"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Sıcak İçecekler"
                        });
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calory")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Portion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calory = 231,
                            CategoryId = 1,
                            Description = "Protein = 20.5m, Fat = 15.3m, Carbonhydrate = 5.7m",
                            Name = "Terbiyeli Köfte",
                            Portion = 0
                        },
                        new
                        {
                            Id = 2,
                            Calory = 343,
                            CategoryId = 1,
                            Description = "Protein = 18.2m, Fat = 28.4m, Carbonhydrate = 3.7m",
                            Name = "İzmir Köfte",
                            Portion = 0
                        },
                        new
                        {
                            Id = 3,
                            Calory = 275,
                            CategoryId = 1,
                            Description = "Protein = 24.8m, Fat = 17.2m, Carbonhydrate = 1.8m",
                            Name = "Fırın Tavuk",
                            Portion = 0
                        },
                        new
                        {
                            Id = 4,
                            Calory = 420,
                            CategoryId = 1,
                            Description = "Protein = 29.5m, Fat = 34.8m, Carbonhydrate = 0.9m",
                            Name = "Kuzu Tandır",
                            Portion = 0
                        },
                        new
                        {
                            Id = 5,
                            Calory = 310,
                            CategoryId = 1,
                            Description = "Protein = 22.1m, Fat = 23.7m, Carbonhydrate = 2.4m",
                            Name = "Köfte Izgara",
                            Portion = 0
                        },
                        new
                        {
                            Id = 6,
                            Calory = 489,
                            CategoryId = 1,
                            Description = "Protein = 24.8m, Fat = 23.2m, Carbonhydrate = 26.8m",
                            Name = "Beyti",
                            Portion = 0
                        },
                        new
                        {
                            Id = 7,
                            Calory = 265,
                            CategoryId = 1,
                            Description = "Protein = 9.4m, Fat = 20.1m, Carbonhydrate = 12.7m",
                            Name = "Patlıcan Kebabı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 8,
                            Calory = 380,
                            CategoryId = 1,
                            Description = "Protein = 22.5m, Fat = 28.6m, Carbonhydrate = 8.3m",
                            Name = "Hünkar Beğendi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 9,
                            Calory = 310,
                            CategoryId = 1,
                            Description = "Protein = 17.8m, Fat = 24.5m, Carbonhydrate = 3.2m",
                            Name = "Cızlak Kebap",
                            Portion = 0
                        },
                        new
                        {
                            Id = 10,
                            Calory = 280,
                            CategoryId = 1,
                            Description = "Protein = 18.6m, Fat = 21.4m, Carbonhydrate = 3.8m",
                            Name = "Ciğer Sote",
                            Portion = 0
                        },
                        new
                        {
                            Id = 11,
                            Calory = 320,
                            CategoryId = 1,
                            Description = "Protein = 20.2m, Fat = 12.5m, Carbonhydrate = 28.1m",
                            Name = "Tavuklu Pilav",
                            Portion = 0
                        },
                        new
                        {
                            Id = 12,
                            Calory = 290,
                            CategoryId = 1,
                            Description = "Protein = 26.8m, Fat = 19.3m, Carbonhydrate = 3.7m",
                            Name = "Fırın Mantarlı Tavuk",
                            Portion = 0
                        },
                        new
                        {
                            Id = 13,
                            Calory = 360,
                            CategoryId = 1,
                            Description = "Protein = 22.3m, Fat = 29.8m, Carbonhydrate = 0.9m",
                            Name = "Dana Kavurma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 14,
                            Calory = 180,
                            CategoryId = 1,
                            Description = "Protein = 3.5m, Fat = 9.2m, Carbonhydrate = 22.8m",
                            Name = "Zeytinyağlı Yaprak Sarma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 15,
                            Calory = 450,
                            CategoryId = 1,
                            Description = "Protein = 30.7m, Fat = 36.2m, Carbonhydrate = 1.2m",
                            Name = "Kuzu İncik",
                            Portion = 0
                        },
                        new
                        {
                            Id = 16,
                            Calory = 260,
                            CategoryId = 1,
                            Description = "Protein = 24.1m, Fat = 17.8m, Carbonhydrate = 0.6m",
                            Name = "Balık Tava",
                            Portion = 0
                        },
                        new
                        {
                            Id = 17,
                            Calory = 310,
                            CategoryId = 1,
                            Description = "Protein = 22.5m, Fat = 23.7m, Carbonhydrate = 2.4m",
                            Name = "Kağıt Kebabı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 18,
                            Calory = 280,
                            CategoryId = 1,
                            Description = "Protein = 19.3m, Fat = 20.1m, Carbonhydrate = 3.8m",
                            Name = "Tavuk Kapama",
                            Portion = 0
                        },
                        new
                        {
                            Id = 19,
                            Calory = 340,
                            CategoryId = 1,
                            Description = "Protein = 21.7m, Fat = 25.2m, Carbonhydrate = 6.3m",
                            Name = "Ali Nazik Kebabı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 20,
                            Calory = 390,
                            CategoryId = 1,
                            Description = "Protein = 28.2m, Fat = 31.6m, Carbonhydrate = 0.9m",
                            Name = "Kuzu Güveç",
                            Portion = 0
                        },
                        new
                        {
                            Id = 21,
                            Calory = 480,
                            CategoryId = 1,
                            Description = "Protein = 26.7m, Fat = 33.2m, Carbonhydrate = 18.4m",
                            Name = "İskender",
                            Portion = 0
                        },
                        new
                        {
                            Id = 22,
                            Calory = 310,
                            CategoryId = 1,
                            Description = "Protein = 24.5m, Fat = 21.2m, Carbonhydrate = 0.8m",
                            Name = "Fırın Tavuk But",
                            Portion = 0
                        },
                        new
                        {
                            Id = 23,
                            Calory = 240,
                            CategoryId = 1,
                            Description = "Protein = 18.2m, Fat = 16.9m, Carbonhydrate = 5.7m",
                            Name = "Tavuklu Karnabahar",
                            Portion = 0
                        },
                        new
                        {
                            Id = 24,
                            Calory = 360,
                            CategoryId = 1,
                            Description = "Protein = 25.6m, Fat = 14.8m, Carbonhydrate = 27.9m",
                            Name = "Balıklı Pilav",
                            Portion = 0
                        },
                        new
                        {
                            Id = 25,
                            Calory = 280,
                            CategoryId = 1,
                            Description = "Protein = 20.3m, Fat = 18.9m, Carbonhydrate = 7.1m",
                            Name = "Hamsili Ekmek",
                            Portion = 0
                        },
                        new
                        {
                            Id = 26,
                            Calory = 290,
                            CategoryId = 1,
                            Description = "Protein = 26.8m, Fat = 19.3m, Carbonhydrate = 3.7m",
                            Name = "Fırın Mantarlı Tavuk",
                            Portion = 0
                        },
                        new
                        {
                            Id = 27,
                            Calory = 420,
                            CategoryId = 1,
                            Description = "Protein = 30.5m, Fat = 34.1m, Carbonhydrate = 1.9m",
                            Name = "Peynirli Kuzu Kuyma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 28,
                            Calory = 380,
                            CategoryId = 1,
                            Description = "Protein = 25.2m, Fat = 29.7m, Carbonhydrate = 5.3m",
                            Name = "Cevizli Kuzu Güveç",
                            Portion = 0
                        },
                        new
                        {
                            Id = 29,
                            Calory = 270,
                            CategoryId = 1,
                            Description = "Protein = 23.4m, Fat = 18.1m, Carbonhydrate = 0.6m",
                            Name = "Fırın Tavuk Kanat",
                            Portion = 0
                        },
                        new
                        {
                            Id = 30,
                            Calory = 320,
                            CategoryId = 1,
                            Description = "Protein = 22.8m, Fat = 24.5m, Carbonhydrate = 3.2m",
                            Name = "Yogurtlu Tavuk Şiş",
                            Portion = 0
                        },
                        new
                        {
                            Id = 31,
                            Calory = 180,
                            CategoryId = 2,
                            Description = "Protein = 6.7m, Fat = 12.4m, Carbonhydrate = 15.8m",
                            Name = "Fırın Karnabahar Kızartması",
                            Portion = 0
                        },
                        new
                        {
                            Id = 32,
                            Calory = 250,
                            CategoryId = 2,
                            Description = "Protein = 14.3m, Fat = 18.6m, Carbonhydrate = 7.9m",
                            Name = "Patlıcanlı Kıymalı Güveç",
                            Portion = 0
                        },
                        new
                        {
                            Id = 33,
                            Calory = 320,
                            CategoryId = 2,
                            Description = "Protein = 22.5m, Fat = 25.1m, Carbonhydrate = 2.8m",
                            Name = "Kuzu Kapama",
                            Portion = 0
                        },
                        new
                        {
                            Id = 34,
                            Calory = 150,
                            CategoryId = 2,
                            Description = "Protein = 4.6m, Fat = 10.2m, Carbonhydrate = 11.8m",
                            Name = "Zeytinyağlı Pırasa",
                            Portion = 0
                        },
                        new
                        {
                            Id = 35,
                            Calory = 200,
                            CategoryId = 2,
                            Description = "Protein = 9.8m, Fat = 12.7m, Carbonhydrate = 13.5m",
                            Name = "Taze Fasulye Türlü",
                            Portion = 0
                        },
                        new
                        {
                            Id = 36,
                            Calory = 280,
                            CategoryId = 2,
                            Description = "Protein = 13.6m, Fat = 19.3m, Carbonhydrate = 16.8m",
                            Name = "Kabak Karnabahar Graten",
                            Portion = 0
                        },
                        new
                        {
                            Id = 37,
                            Calory = 320,
                            CategoryId = 2,
                            Description = "Protein = 18.7m, Fat = 24.5m, Carbonhydrate = 7.2m",
                            Name = "Sebzeli Kıymalı Börek",
                            Portion = 0
                        },
                        new
                        {
                            Id = 38,
                            Calory = 180,
                            CategoryId = 2,
                            Description = "Protein = 4.2m, Fat = 13.8m, Carbonhydrate = 11.5m",
                            Name = "Zeytinyağlı Enginar",
                            Portion = 0
                        },
                        new
                        {
                            Id = 39,
                            Calory = 240,
                            CategoryId = 2,
                            Description = "Protein = 12.3m, Fat = 18.9m, Carbonhydrate = 6.5m",
                            Name = "Kırmızı Mercimek Koftesi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 40,
                            Calory = 210,
                            CategoryId = 2,
                            Description = "Protein = 8.5m, Fat = 14.2m, Carbonhydrate = 16.7m",
                            Name = "Karnabahar Köftesi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 41,
                            Calory = 180,
                            CategoryId = 3,
                            Description = "Protein = 6.5m, Fat = 9.2m, Carbonhydrate = 19.8m",
                            Name = "Quinoa Salatası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 42,
                            Calory = 220,
                            CategoryId = 3,
                            Description = "Protein = 5.8m, Fat = 17.1m, Carbonhydrate = 11.3m",
                            Name = "Cevizli Kabak Tarator",
                            Portion = 0
                        },
                        new
                        {
                            Id = 43,
                            Calory = 250,
                            CategoryId = 3,
                            Description = "Protein = 7.3m, Fat = 12.9m, Carbonhydrate = 28.4m",
                            Name = "Karnabahar Kuskusu",
                            Portion = 0
                        },
                        new
                        {
                            Id = 44,
                            Calory = 290,
                            CategoryId = 3,
                            Description = "Protein = 6.7m, Fat = 1.5m, Carbonhydrate = 61.2m",
                            Name = "Bulgur Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 45,
                            Calory = 310,
                            CategoryId = 3,
                            Description = "Protein = 8.2m, Fat = 4.6m, Carbonhydrate = 66.5m",
                            Name = "İncirli Armut Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 46,
                            Calory = 180,
                            CategoryId = 3,
                            Description = "Protein = 5.4m, Fat = 3.2m, Carbonhydrate = 33.5m",
                            Name = "Yulaf Ezmesi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 47,
                            Calory = 320,
                            CategoryId = 3,
                            Description = "Protein = 6.9m, Fat = 1.8m, Carbonhydrate = 69.4m",
                            Name = "Pirinç Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 48,
                            Calory = 250,
                            CategoryId = 3,
                            Description = "Protein = 7.8m, Fat = 3.5m, Carbonhydrate = 47.2m",
                            Name = "Fasulye Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 49,
                            Calory = 280,
                            CategoryId = 3,
                            Description = "Protein = 10.1m, Fat = 4.7m, Carbonhydrate = 53.8m",
                            Name = "Beyaz Nohut Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 50,
                            Calory = 210,
                            CategoryId = 3,
                            Description = "Protein = 5.9m, Fat = 2.1m, Carbonhydrate = 43.7m",
                            Name = "Kabaklı Bulgur Pilavı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 51,
                            Calory = 180,
                            CategoryId = 4,
                            Description = "Protein = 3.5m, Fat = 12.6m, Carbonhydrate = 15.2m",
                            Name = "Zeytinyağlı Yaprak Sarma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 52,
                            Calory = 150,
                            CategoryId = 4,
                            Description = "Protein = 2.8m, Fat = 10.3m, Carbonhydrate = 12.4m",
                            Name = "Zeytinyağlı Kabak Dolması",
                            Portion = 0
                        },
                        new
                        {
                            Id = 53,
                            Calory = 120,
                            CategoryId = 4,
                            Description = "Protein = 2.4m, Fat = 8.1m, Carbonhydrate = 9.7m",
                            Name = "Zeytinyağlı Pırasa",
                            Portion = 0
                        },
                        new
                        {
                            Id = 54,
                            Calory = 140,
                            CategoryId = 4,
                            Description = "Protein = 3.1m, Fat = 8.8m, Carbonhydrate = 11.5m",
                            Name = "Zeytinyağlı Taze Fasulye",
                            Portion = 0
                        },
                        new
                        {
                            Id = 55,
                            Calory = 200,
                            CategoryId = 4,
                            Description = "Protein = 4.6m, Fat = 15.4m, Carbonhydrate = 14.7m",
                            Name = "Zeytinyağlı Enginar",
                            Portion = 0
                        },
                        new
                        {
                            Id = 56,
                            Calory = 160,
                            CategoryId = 4,
                            Description = "Protein = 3.2m, Fat = 11.5m, Carbonhydrate = 12.9m",
                            Name = "Zeytinyağlı Karnabahar",
                            Portion = 0
                        },
                        new
                        {
                            Id = 57,
                            Calory = 130,
                            CategoryId = 4,
                            Description = "Protein = 2.9m, Fat = 8.6m, Carbonhydrate = 10.7m",
                            Name = "Zeytinyağlı Bamya",
                            Portion = 0
                        },
                        new
                        {
                            Id = 58,
                            Calory = 110,
                            CategoryId = 4,
                            Description = "Protein = 2.1m, Fat = 7.2m, Carbonhydrate = 9.4m",
                            Name = "Zeytinyağlı Ispanak",
                            Portion = 0
                        },
                        new
                        {
                            Id = 59,
                            Calory = 140,
                            CategoryId = 4,
                            Description = "Protein = 3.3m, Fat = 9.2m, Carbonhydrate = 11.8m",
                            Name = "Zeytinyağlı Pırasa Yemeği",
                            Portion = 0
                        },
                        new
                        {
                            Id = 60,
                            Calory = 150,
                            CategoryId = 4,
                            Description = "Protein = 3.7m, Fat = 9.8m, Carbonhydrate = 12.5m",
                            Name = "Zeytinyağlı Taze Fasulye Pilaki",
                            Portion = 0
                        },
                        new
                        {
                            Id = 71,
                            Calory = 150,
                            CategoryId = 5,
                            Description = "Protein = 9.5m, Fat = 3.2m, Carbonhydrate = 21.8m",
                            Name = "Mercimek Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 72,
                            Calory = 120,
                            CategoryId = 5,
                            Description = "Protein = 7.8m, Fat = 5.1m, Carbonhydrate = 12.6m",
                            Name = "Tarator Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 73,
                            Calory = 110,
                            CategoryId = 5,
                            Description = "Protein = 4.2m, Fat = 2.8m, Carbonhydrate = 18.5m",
                            Name = "Domates Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 74,
                            Calory = 180,
                            CategoryId = 5,
                            Description = "Protein = 12.3m, Fat = 4.6m, Carbonhydrate = 23.7m",
                            Name = "Tavuklu Şehriye Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 75,
                            Calory = 160,
                            CategoryId = 5,
                            Description = "Protein = 8.9m, Fat = 3.5m, Carbonhydrate = 24.2m",
                            Name = "Ezogelin Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 76,
                            Calory = 140,
                            CategoryId = 5,
                            Description = "Protein = 7.4m, Fat = 6.8m, Carbonhydrate = 15.9m",
                            Name = "Yoğurtlu Çorba",
                            Portion = 0
                        },
                        new
                        {
                            Id = 77,
                            Calory = 220,
                            CategoryId = 5,
                            Description = "Protein = 5.6m, Fat = 18.3m, Carbonhydrate = 9.7m",
                            Name = "Kremalı Mantar Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 78,
                            Calory = 130,
                            CategoryId = 5,
                            Description = "Protein = 3.7m, Fat = 7.2m, Carbonhydrate = 14.8m",
                            Name = "Kabak Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 79,
                            Calory = 160,
                            CategoryId = 5,
                            Description = "Protein = 9.8m, Fat = 2.6m, Carbonhydrate = 25.4m",
                            Name = "Kırmızı Mercimek Çorbası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 80,
                            Calory = 528,
                            CategoryId = 6,
                            Description = "Protein = 7.6m, Fat = 29.8m, Carbonhydrate = 63.3m",
                            Name = "İrmik Helvası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 81,
                            Calory = 347,
                            CategoryId = 6,
                            Description = "Protein = 8.2m, Fat = 7.2m, Carbonhydrate = 67.2m",
                            Name = "Sütlaç",
                            Portion = 0
                        },
                        new
                        {
                            Id = 82,
                            Calory = 450,
                            CategoryId = 6,
                            Description = "Protein = 7.5m, Fat = 29.5m, Carbonhydrate = 40.2m",
                            Name = "Baklava",
                            Portion = 0
                        },
                        new
                        {
                            Id = 83,
                            Calory = 280,
                            CategoryId = 6,
                            Description = "Protein = 5.8m, Fat = 12.6m, Carbonhydrate = 35.2m",
                            Name = "Kazandibi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 84,
                            Calory = 315,
                            CategoryId = 6,
                            Description = "Protein = 6.2m, Fat = 15.8m, Carbonhydrate = 38.1m",
                            Name = "Revani",
                            Portion = 0
                        },
                        new
                        {
                            Id = 85,
                            Calory = 207,
                            CategoryId = 6,
                            Description = "Protein = 5.4m, Fat = 11.2m, Carbonhydrate = 22.6m",
                            Name = "Dondurma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 86,
                            Calory = 127,
                            CategoryId = 7,
                            Description = "Protein = 2.5m, Fat = 8.4m, Carbonhydrate = 11.6m",
                            Name = "Domates Salatası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 87,
                            Calory = 75,
                            CategoryId = 7,
                            Description = "Protein = 3.2m, Fat = 5.6m, Carbonhydrate = 3.9m",
                            Name = "Cacık",
                            Portion = 0
                        },
                        new
                        {
                            Id = 88,
                            Calory = 64,
                            CategoryId = 7,
                            Description = "Protein = 3.9m, Fat = 4.7m, Carbonhydrate = 2.9m",
                            Name = "Roka Salatası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 89,
                            Calory = 184,
                            CategoryId = 7,
                            Description = "Protein = 4.8m, Fat = 16.7m, Carbonhydrate = 3.2m",
                            Name = "Ceasar Salatası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 90,
                            Calory = 95,
                            CategoryId = 7,
                            Description = "Protein = 3.1m, Fat = 6.4m, Carbonhydrate = 7.6m",
                            Name = "Mevsim Salatası",
                            Portion = 0
                        },
                        new
                        {
                            Id = 92,
                            Calory = 63,
                            CategoryId = 8,
                            Description = "Protein = 1.0m, Fat = 0.2m, Carbonhydrate = 15.3m",
                            Name = "Kayısı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 93,
                            Calory = 96,
                            CategoryId = 8,
                            Description = "Protein = 1.3m, Fat = 0.3m, Carbonhydrate = 25.0m",
                            Name = "Muz",
                            Portion = 0
                        },
                        new
                        {
                            Id = 94,
                            Calory = 63,
                            CategoryId = 8,
                            Description = "Protein = 1.1m, Fat = 0.2m, Carbonhydrate = 16.0m",
                            Name = "Kiraz",
                            Portion = 0
                        },
                        new
                        {
                            Id = 95,
                            Calory = 69,
                            CategoryId = 8,
                            Description = "Protein = 0.7m, Fat = 0.2m, Carbonhydrate = 17.5m",
                            Name = "Üzüm",
                            Portion = 0
                        },
                        new
                        {
                            Id = 96,
                            Calory = 73,
                            CategoryId = 8,
                            Description = "Protein = 0.9m, Fat = 0.2m, Carbonhydrate = 18.0m",
                            Name = "Kavun",
                            Portion = 0
                        },
                        new
                        {
                            Id = 97,
                            Calory = 30,
                            CategoryId = 8,
                            Description = "Protein = 0.6m, Fat = 0.2m, Carbonhydrate = 8.0m",
                            Name = "Karpuz",
                            Portion = 0
                        },
                        new
                        {
                            Id = 98,
                            Calory = 43,
                            CategoryId = 8,
                            Description = "Protein = 1.0m, Fat = 0.2m, Carbonhydrate = 8.3m",
                            Name = "Portakal",
                            Portion = 0
                        },
                        new
                        {
                            Id = 99,
                            Calory = 70,
                            CategoryId = 8,
                            Description = "Protein = 0.8m, Fat = 0.2m, Carbonhydrate = 13.5m",
                            Name = "Mandalina",
                            Portion = 0
                        },
                        new
                        {
                            Id = 100,
                            Calory = 38,
                            CategoryId = 8,
                            Description = "Protein = 0.9m, Fat = 0.2m, Carbonhydrate = 9.6m",
                            Name = "Malta eriği",
                            Portion = 0
                        },
                        new
                        {
                            Id = 101,
                            Calory = 52,
                            CategoryId = 8,
                            Description = "Protein = 0.3m, Fat = 0.2m, Carbonhydrate = 14.0m",
                            Name = "Elma",
                            Portion = 0
                        },
                        new
                        {
                            Id = 102,
                            Calory = 76,
                            CategoryId = 9,
                            Description = "Protein = 0.0m, Fat = 0.0m, Carbonhydrate = 20.0m",
                            Name = "Toz Şeker",
                            Portion = 0
                        },
                        new
                        {
                            Id = 103,
                            Calory = 121,
                            CategoryId = 9,
                            Description = "Protein = 6.0m, Fat = 10.0m, Carbonhydrate = 1.0m",
                            Name = "Peynir (Kaşar)",
                            Portion = 0
                        },
                        new
                        {
                            Id = 104,
                            Calory = 87,
                            CategoryId = 9,
                            Description = "Protein = 7.0m, Fat = 6.0m, Carbonhydrate = 1.0m",
                            Name = "Peynir(Beyaz)",
                            Portion = 0
                        },
                        new
                        {
                            Id = 105,
                            Calory = 96,
                            CategoryId = 9,
                            Description = "Protein = 0.3m, Fat = 0.1m, Carbonhydrate = 25.0m",
                            Name = "Reçel",
                            Portion = 0
                        },
                        new
                        {
                            Id = 106,
                            Calory = 221,
                            CategoryId = 9,
                            Description = "Protein = 0.3m, Fat = 24.0m, Carbonhydrate = 0.0m",
                            Name = "Yağ(Margarin)",
                            Portion = 0
                        },
                        new
                        {
                            Id = 107,
                            Calory = 80,
                            CategoryId = 9,
                            Description = "Protein = 6.0m, Fat = 5.0m, Carbonhydrate = 1.0m",
                            Name = "Yumurta",
                            Portion = 0
                        },
                        new
                        {
                            Id = 108,
                            Calory = 43,
                            CategoryId = 9,
                            Description = "Protein = 0.5m, Fat = 4.0m, Carbonhydrate = 0.0m",
                            Name = "Zeytin(Yeşil)",
                            Portion = 0
                        },
                        new
                        {
                            Id = 109,
                            Calory = 62,
                            CategoryId = 9,
                            Description = "Protein = 0.5m, Fat = 6.0m, Carbonhydrate = 1.0m",
                            Name = "Zeytin(Siyah)",
                            Portion = 0
                        },
                        new
                        {
                            Id = 110,
                            Calory = 276,
                            CategoryId = 9,
                            Description = "Protein = 9.0m, Fat = 1.0m, Carbonhydrate = 56.0m",
                            Name = "Ekmek",
                            Portion = 0
                        },
                        new
                        {
                            Id = 111,
                            Calory = 61,
                            CategoryId = 10,
                            Description = "Protein = 3.0m, Fat = 3.0m, Carbonhydrate = 5.0m",
                            Name = "İnek Sütü",
                            Portion = 0
                        },
                        new
                        {
                            Id = 112,
                            Calory = 63,
                            CategoryId = 10,
                            Description = "Protein = 4.0m, Fat = 3.0m, Carbonhydrate = 4.0m",
                            Name = "Yoğurt",
                            Portion = 0
                        },
                        new
                        {
                            Id = 115,
                            Calory = 140,
                            CategoryId = 11,
                            Description = "Protein = 0.0m, Fat = 0.0m, Carbonhydrate = 39.0m",
                            Name = "Kola",
                            Portion = 0
                        },
                        new
                        {
                            Id = 116,
                            Calory = 110,
                            CategoryId = 11,
                            Description = "Protein = 2.0m, Fat = 0.5m, Carbonhydrate = 26.0m",
                            Name = "Portakal Suyu",
                            Portion = 0
                        },
                        new
                        {
                            Id = 117,
                            Calory = 120,
                            CategoryId = 11,
                            Description = "Protein = 0.5m, Fat = 0.0m, Carbonhydrate = 30.0m",
                            Name = "Limonata",
                            Portion = 0
                        },
                        new
                        {
                            Id = 118,
                            Calory = 90,
                            CategoryId = 11,
                            Description = "Protein = 0.0m, Fat = 0.0m, Carbonhydrate = 24.0m",
                            Name = "Gazoz",
                            Portion = 0
                        },
                        new
                        {
                            Id = 119,
                            Calory = 200,
                            CategoryId = 11,
                            Description = "Protein = 2.5m, Fat = 1.0m, Carbonhydrate = 45.0m",
                            Name = "Meyve Smoothie",
                            Portion = 0
                        },
                        new
                        {
                            Id = 120,
                            Calory = 5,
                            CategoryId = 12,
                            Description = "Protein = 0.5m, Fat = 0.2m, Carbonhydrate = 0.0m",
                            Name = "Türk Kahvesi",
                            Portion = 0
                        },
                        new
                        {
                            Id = 121,
                            Calory = 2,
                            CategoryId = 12,
                            Description = "Protein = 0.1m, Fat = 0.0m, Carbonhydrate = 0.5m",
                            Name = "Siyah Çay",
                            Portion = 0
                        },
                        new
                        {
                            Id = 122,
                            Calory = 0,
                            CategoryId = 12,
                            Description = "Protein = 0.0m, Fat = 0.0m, Carbonhydrate = 0.0m",
                            Name = "Yeşil Çay",
                            Portion = 0
                        },
                        new
                        {
                            Id = 123,
                            Calory = 4,
                            CategoryId = 12,
                            Description = "Protein = 0.1m, Fat = 0.0m, Carbonhydrate = 0.8m",
                            Name = "Nane Limon Çayı",
                            Portion = 0
                        },
                        new
                        {
                            Id = 124,
                            Calory = 150,
                            CategoryId = 12,
                            Description = "Protein = 1.5m, Fat = 2.0m, Carbonhydrate = 30.0m",
                            Name = "Salep",
                            Portion = 0
                        });
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.FoodMeal", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("MealId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("FoodMeals");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar");

                    b.Property<int>("UserDailyActivityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserDailyActivityId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("Gender")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Weight")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.UserDailyActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activity")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShouldTakenCalories")
                        .HasColumnType("int");

                    b.Property<int>("StepCount")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserDailyActivities");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Food", b =>
                {
                    b.HasOne("StayFIT_CORE.Concrete.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.FoodMeal", b =>
                {
                    b.HasOne("StayFIT_CORE.Concrete.Food", "Food")
                        .WithMany("FoodMeals")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StayFIT_CORE.Concrete.Meal", "Meal")
                        .WithMany("FoodMeals")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Meal", b =>
                {
                    b.HasOne("StayFIT_CORE.Concrete.UserDailyActivity", "UserDailyActivity")
                        .WithMany("Meals")
                        .HasForeignKey("UserDailyActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDailyActivity");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.UserDailyActivity", b =>
                {
                    b.HasOne("StayFIT_CORE.Concrete.User", "User")
                        .WithMany("UserDailyActivity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Category", b =>
                {
                    b.Navigation("Foods");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Food", b =>
                {
                    b.Navigation("FoodMeals");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.Meal", b =>
                {
                    b.Navigation("FoodMeals");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.User", b =>
                {
                    b.Navigation("UserDailyActivity");
                });

            modelBuilder.Entity("StayFIT_CORE.Concrete.UserDailyActivity", b =>
                {
                    b.Navigation("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
